<html>
<head>
<title>管理中心</title>
<meta http-equiv=Content-Type content=text/html;charset="utf-8">
</head>
  <frameset cols="200,*"  id="frame" frameborder=1>
	<frame src="{%$baseUrl%}/hapyfish/left" name="leftFrame" noresize="noresize" marginwidth="0" marginheight="0" frameborder="0" scrolling="no" target="main" />
	<frame src="{%$baseUrl%}/hapyfish/list?column_no=999001" name="main" marginwidth="0" marginheight="0" frameborder="0" scrolling="auto" target="_self" />
  </frameset>
  <noframes>
	<body></body>
  </noframes>
</html>
