<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>快乐森林ipanda捐赠</title>
<script src="http://a.tbcdn.cn/apps/mytaobao/1.0/proxy.js" type="text/javascript"></script>
<script type="text/javascript" src="{%$staticUrl%}/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="{%$staticUrl%}/js/jquery-ui-1.8.16.custom.min.js"></script>
<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
<link type="text/css" href="{%$staticUrl%}/js/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
<style type="text/css">
<!--
body {
	background-image: url({%$staticUrl%}/ipanda/pages/images/bg.jpg);
	background-repeat: repeat-x;
	margin-left: 0px;
	margin-top: 00px;
	margin-right: 0px;
	margin-bottom: 0px;
}
.STYLE4 {font-size: 10pt; }
-->
</style></head>

<body>
    <div style="height:1049px;" align="center">
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_02.jpg" width="994" height="111" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_06.jpg" width="994" height="40" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="678"><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_07.jpg" width="678" height="194" alt="" /></td>
          <td width="158"><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_08.jpg" width="236" height="194" alt="" /></td>
          <td width="158"><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_09.jpg" width="80" height="194" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_10.jpg" width="994" height="66" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_11.jpg" width="351" height="265" alt="" /></td>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_12.jpg" width="336" height="265" alt="" /></td>
          <td><table width="307" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_13.jpg" width="42" height="215" alt="" /></td>
              <td><table width="172" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_14.jpg" width="172" height="99" alt="" /></td>
                </tr>
              </table>
              	<!--<form action="" method="post" name="form1" class="STYLE4" id="form1">-->
                <table width="172" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
                  <tr>
                    <td height="30"><table width="150" height="99" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td>
                          <label>
                          <input type="radio" name="radio" id="radio1" value="1" checked/>
                          </label>
                          1元
                        </td>
                        <td><span class="STYLE4">
                          <input type="radio" name="radio" id="radio2" value="5" />
                          5元</span></td>
                      </tr>
                      <tr>
                        <td><span class="STYLE4">
                          <input type="radio" name="radio" id="radio3" value="10" />
                          10元</span></td>
                        <td><span class="STYLE4">
                          <input type="radio" name="radio" id="radio4" value="50" />
                          50元</span></td>
                      </tr>
                      <tr>
                        <td><span class="STYLE4">
                          <input type="radio" name="radio" id="radio5" value="100" />
                          100元</span></td>
                        <td>&nbsp;</td>
                      </tr>
                      <!-- <tr><td><a href="#" id="btn2">捐赠爱心榜</a></td></tr> -->
                    </table></td>
                  </tr>
                </table></td>
              <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_15.jpg" width="93" height="215" alt="" /></td>
            </tr>
          </table>	<!--</form>-->
            <table width="307" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td><a href="#"><img style="border:none" id="btn1" src="{%$staticUrl%}/ipanda/pages/images/panda_cut_17_ok.jpg" width="307" height="50" alt="" /></a></td>
              </tr>
            </table></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_18.jpg" width="994" height="53" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_19.jpg" width="351" height="192" alt="" /></td>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_20.jpg" width="643" height="192" alt="" /></td>
        </tr>
      </table>
      <table width="994" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="{%$staticUrl%}/ipanda/pages/images/panda_cut_21.jpg" width="994" height="128" alt="" /></td>
        </tr>
      </table>
    </div>

    <div id="dialog-modal" title="Basic modal dialog">
    	<div id="divList"><img src="{%$staticUrl%}/ipanda/image/common/loading0.gif" /><br/>加载中......</div>
    </div>

    <div>
    <form id="frmDonate" method="post" action="{%$actionUrl%}">
		<input type="hidden" value="" id="_input_charset" name="_input_charset" />
		<input type="hidden" value="" id="service" name="service" />
		<input type="hidden" value="" id="partner" name="partner" />
		<input type="hidden" value="" id="donate_item_name" name="donate_item_name" />
		<input type="hidden" value="" id="out_trade_no" name="out_trade_no" />
		<input type="hidden" value="" id="total_fee" name="total_fee" />
		<input type="hidden" value="" id="notify_url" name="notify_url" />
		<input type="hidden" value="" id="return_url" name="return_url" />
		<!-- <input type="hidden" value="" id="buyer_account_name" name="buyer_account_name" /> -->
		<input type="hidden" value="" id="sign" name="sign" />
		<input type="hidden" value="" id="sign_type" name="sign_type" />
	</form>
	<script type="text/javascript">
    	$(document).ready(function() {
        	$("#btn1").unbind('click');
    	    $("#btn1").click(donate);

    	    //$("#btn2").unbind('click');
    	    //$("#btn2").click(listDonate);
        });

    	function donate(type) {
    		var fee = $("input[type='radio']:checked").val();
    		if (!fee) {
				return false;
        	}

    		$('#btn1').attr('disabled', true);

    		$.ajax({
            	type: 'POST',
    			url: '/donate/createtrade',
    			data: {"fee": fee},
    			dataType: 'json',
    			success: function(resp) {
    				if(resp == '' || resp == null) {
    					alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
    				} else {
    					$('#_input_charset').val(resp._input_charset);
                    	$('#service').val(resp.service);
                    	$('#partner').val(resp.partner);
                    	$('#donate_item_name').val(resp.donate_item_name);
                    	$('#out_trade_no').val(resp.out_trade_no);
                    	$('#total_fee').val(resp.total_fee);
                    	$('#notify_url').val(resp.notify_url);
                    	$('#return_url').val(resp.return_url);
                    	//$('#buyer_account_name').val(resp.buyer_account_name);
                    	$('#sign').val(resp.sign);
                    	$('#sign_type').val(resp.sign_type);
                    	$('#frmDonate').submit();
    				}
    			},
    			error: function(resp) {
    				alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
        			ffdebug('err:'+resp);
        		},
        		complete: function(resp) {
        			//ffdebug('complete:'+resp);
        			$('#btn1').attr('disabled', false);
        		}
    		});
    	}

    	function listDonate() {
    		$('#btn2').attr('disabled', true);
    		$.ajax({
            	type: 'POST',
    			url: '/donate/listdonate',
    			dataType: 'json',
    			success: function(resp) {
    				if(resp == '' || resp == null) {
    				} else {
    					LOG_LIST = resp.list;
    					LOG_NUM = parseInt(resp.count);
    					LOG_PER_PAGE = parseInt(resp.pageSize);
    					LOG_PAGE_NUM = parseInt(resp.pageNum);
    					showPage(1);

    		    		$( "#dialog:ui-dialog" ).dialog( "destroy" );
    		    		$( "#dialog-modal" ).dialog({
    		    			width: 600,
    		    			modal: true,
    		    			resizable: false,
    		    			title: '捐赠爱心榜'
    		    		});
    				}
    			},
    			error: function(resp) {
        			ffdebug('err:'+resp);
        		},
        		complete: function(resp) {
        			//ffdebug('complete:'+resp);
        			$('#btn2').attr('disabled', false);
        		}
    		});
    	}

    	var LOG_LIST;
    	var LOG_NUM;
    	var LOG_PER_PAGE;
    	var LOG_PAGE_NUM;

    	function timeFormat(time)
    	{
    		var timestamp = time*1000;
    		return (new Date(timestamp)).format('Y-m-d H:i:s');
    	}

    	function showPage(i)
    	{
    		if (i <= 0 || i > LOG_PAGE_NUM) {
    			return;
    		}
    		var html = '<table width="580" border="0" align="center" cellpadding="0" cellspacing="0" >';
    		if (LOG_NUM == 0) {
    			html += '<tr><td colspan="3">还没有捐赠记录</td></tr>';
    		} else {
    			var start = (i-1) * LOG_PER_PAGE;
    			var end = start + LOG_PER_PAGE;
    			if (end > LOG_NUM) {
    				end = LOG_NUM;
    			}
    			html += '<tr><td width="230">捐赠时间</td><td width="240">捐赠人</td><td>捐赠金额</td></tr>';
    			for(var j = start; j < end; j++) {
    				html += '<tr class="table-line"><td>' + timeFormat(LOG_LIST[j].complete_time) + '</td><td>'
    					 + LOG_LIST[j].name + '</td><td align="center"><span class="pay-count">￥'
    					 + LOG_LIST[j].amount + '</td></tr>';
    			}
    		}
    		html += '</table><br/><br/><div align="center">页码：';
    		if (i > 1) {
    			html += '<a href="javascript:void(0);" onclick="showPage(' + (i-1) + ');"> ' + '上一页 </a>&nbsp;';
    		}
    		for(j = 1; j <= LOG_PAGE_NUM; j++) {
    			html += '<a href="javascript:void(0);" onclick="showPage(' + j + ');"> ' + j + ' </a>&nbsp;';
    		}
    		if (i < LOG_PAGE_NUM) {
    			html += '<a href="javascript:void(0);" onclick="showPage(' + (i+1) + ');"> ' + '下一页 </a>&nbsp;';
    		}
    		html += '</div>';
    		$('#divList').html(html);
    	}

        function ffdebug(content) {
        	if (window.console && console.debug) {
    			console.debug(content);
      		}
        }
	</script>
    </div>
</body>
</html>