<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐森林</title>
<link href="{%$staticUrl%}/apps/island/main_2011041101.css?v=1.01" rel="stylesheet" type="text/css" />
<link href="{%$staticUrl%}/apps/island/pay_2011031501.css?v=1.00" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}
-->
</style>
</head>
<body>
<div class="main" id="top">
{%include file="menu.phtml"%}

    <div class="chongzhicontent">
    	<img src="{%$user.face%}" width="59" height="60" />
    	<div class="xinxi">
    		<div class="cname">{%$user.name|escape%}</div>
    		<div class="shuzi">宝石： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
    		<div class="fhyx"><a href="http://i.taobao.com/apps/show.htm?appkey=12029234" target="_top"><img src="{%$staticUrl%}/apps/island/images/pay/back.gif" width="80" height="35" /></a></div>
    	</div>
    </div>

    <div class="table">
    	<ul>
    	<li style="width:50px"></li>
    	<li><a href="{%$baseUrl%}/pay/top"><div class="nav_02">充值宝石</div></a></li>
    	<li><a href="{%$baseUrl%}/pay/log"><div class="nav_02">充值记录</div></a></li>
    	<li><a href="{%$baseUrl%}/consumelogs/gold"><div class="nav_02">消费记录</div></a></li>
    	<li><a href="{%$baseUrl%}/pay/listorder"><div class="nav_01">订单查询</div></a></li>
    	</ul>
    </div>

	<div class="content" style="padding-top:10px;width:750px;">
		<div class="chongzhi02"><span style="color:#0C67B6">支付记录</span> &nbsp;&nbsp;共{%$count%}条 </div>
		<table width="720" border="0" align="center" cellpadding="0" cellspacing="0" class="congzhitable">
		<tr>
			<td width="150"><strong>日期</strong></td>
			<td width="100"><strong>充值宝石数量</strong></td>
			<td width="100"><strong>消费</strong></td>
			<td width="200"><strong>订单号</strong></td>
			<td width="100"><strong>状态</strong></td>
			<td width="60"><strong></strong></td>
		</tr>
{%if $count>0 %}
{% foreach from=$logs item=log %}
		<tr class="table-line">
    		<td>{%$log.order_time|date_format:"%Y-%m-%d %H:%M:%S"%}</td>
    		<td><span class="pay-count">{%$log.gold%}</span></td>
    		<td>{%$log.amount%}元</td>
    		<td>{%$log.orderid%}</td>
    		<td>{%if $log.status%}支付完成{%else%}未完成{%/if%}</td>
    		<td>{%if $log.status%}{%else%}<a href="{%$baseUrl%}/pay/getorder?id={%$log.orderid%}">查询</a>{%/if%}</td>
  		</tr>
{%/foreach%}
{% /if %}
		</table>
	</div>
</div>
</body>
</html>