
<link href="{%$staticUrl%}/ipanda/pay_2011121201.css?v=1.00" rel="stylesheet" type="text/css" />
<style type="text/css">
    html, body { height:100%; }
    body { margin:0; }
</style>

<div class="main">
    <div class="chongzhicontent">
    	<img src="{%$user.face%}" width="59" height="60" />
    	<div class="xinxi">
    		<div class="cname">{%$user.name|escape%}</div>
    		<div class="shuzi" style="background-image:url({%$staticUrl%}/ipanda/image/pay/jinbi.png)">金币： <span style="color:#3c7e9a;font-weight:bold;">{%$user.gold%}</span></div>
    	</div>
    </div>

    <div class="table">
    	<ul>
    	<li style="width:50px"></li>
    	<li><a href="#" onclick="showPay(1);"><div class="nav_02">充值</div></a></li>
    	<li><a href="#"><div class="nav_01">充值记录</div></a></li>
    	<!-- <li><a href="{%$baseUrl%}/consumelogs/gold"><div class="nav_02">消费记录</div></a></li>
    	<li><a href="{%$baseUrl%}/pay/listorder"><div class="nav_02">订单查询</div></a></li> -->
    	</ul>
    </div>

	<div class="content" style="padding-top:10px;width:750px;">
		<div class="chongzhi02"><span style="color:#0C67B6">充值记录(最多显示最新的50条)</span></div>
		<table width="720" border="0" align="center" cellpadding="0" cellspacing="0" class="congzhitable">
		<tr>
			<td width="120"><strong>日期</strong></td>
			<td width="140" align="center"><strong>金额</strong></td>
			<td><strong>充值信息摘要</strong></td>
		</tr>
		</table>
		<div id="logdata"></div>
	</div>

<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
<script type="text/javascript">
var LOG_LIST = {%$logs%};
var LOG_NUM = {%$count%};
var LOG_PER_PAGE = {%$pageSize%};
var LOG_PAGE_NUM = {%$pageNum%};

function timeFormat(time)
{
	var timestamp = time*1000;
	return (new Date(timestamp)).format('Y-m-d H:i:s');
}

function showPage(i)
{
	if (i <= 0 || i > LOG_PAGE_NUM) {
		return;
	}
	var html = '<table width="720" border="0" align="center" cellpadding="0" cellspacing="0" class="congzhitable">';
	if (LOG_NUM == 0) {
		html += '<tr><td colspan="3">您还没有充值记录</td></tr>';
	} else {
		var start = (i-1) * LOG_PER_PAGE;
		var end = start + LOG_PER_PAGE;
		if (end > LOG_NUM) {
			end = LOG_NUM;
		}
		for(var j = start; j < end; j++) {
			html += '<tr class="table-line"><td width="120">' + timeFormat(LOG_LIST[j].create_time) + '</td><td width="140" align="center"><span class="pay-count">'
				 + LOG_LIST[j].amount + '</td><td>'
				 + LOG_LIST[j].summary + '</td></tr>';
		}
	}
	html += '</table><div align="center" style="width:720px">';
	if (i > 1) {
		html += '<a href="javascript:void(0);" onclick="showPage(' + (i-1) + ');"> ' + '上一页 </a>&nbsp;';
	}
	for(j = 1; j <= LOG_PAGE_NUM; j++) {
		html += '<a href="javascript:void(0);" onclick="showPage(' + j + ');"> ' + j + ' </a>&nbsp;';
	}
	if (i < LOG_PAGE_NUM) {
		html += '<a href="javascript:void(0);" onclick="showPage(' + (i+1) + ');"> ' + '下一页 </a>&nbsp;';
	}
	html += '</div>';
	$('#logdata').html(html);
}

showPage(1);
</script>