<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐森林</title>
<script src="http://a.tbcdn.cn/apps/mytaobao/1.0/proxy.js" type="text/javascript"></script>
<script src="http://a.tbcdn.cn/s/kissy/1.2.0/kissy-min.js" type="text/javascript"></script>
<script src="http://a.tbcdn.cn/apps/snstaoshare/widget/ts/ts-min.js"></script>
<script src="http://a.tbcdn.cn/apps/snstaoshare/widget/ts/share/2.0/main.js?t=2011101" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
<script type="text/javascript" src="{%$staticUrl%}/js/jquery-ui-1.8.16.custom.min.js"></script>
<script src="{%$staticUrl%}/js/utils.js?v=1.0" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/hf-app.js?v=1.0" type="text/javascript"></script>
<!-- <script src="{%$staticUrl%}/js/hf-check.js?v=1.0" type="text/javascript"></script> -->
<link type="text/css" href="{%$staticUrl%}/js/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
<link href="{%$staticUrl%}/ipanda/main_2011041101.css?v=1.02" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
a img,:link img,:visited img {
	border: 0 none;
}

object#swfcontent {
	display: inline;
}

.box {
	border: 1px solid #CCCCCC;
}
-->
</style>
</head>
<body>
<div class="main" style="height:750px;">
	{%include file="menu.phtml"%}
	<div style="clear:both;"></div>
	<div id="main_content">
		<div id="loadingdiv" style="position: absolute; left: 350px; top: 250px;"><img src="{%$staticUrl%}/ipanda/image/common/loading0.gif" /><br/>加载中......</div>
		<div id="flashdiv"></div>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;
			var FIRST_LOGIN = {%$newuser%};

			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
	        	var flashVars={"uid":"{%$uid%}","newUser":{%$newuser%},"isLocal":"false","initUi":"{%$staticUrl%}/swf/loadingMovie.swf?v=2011121201","initInterface":"{%$hostUrl%}/api/assetlist?v={%$ver_asset%}", "initData":"{%$hostUrl%}/api/initdata?v={%$ver_initData%}","snsType":"taobao","tipsStr":"全屏操作更方便哟！||除了建培育屋，还要帮动物建设他们喜欢的建筑哦！||正确回答熊猫的问题能额外获得奖励哦||等级越高体力越多哦！||等级越高出现的动物会越来越多哦！||去好友家领养动物，自己的森林里一定要有这个动物的建筑哟！||体力不够时除了吃蛋糕，不急的话可以休息恢复2分钟恢复一体力！||发现动物头上的黄色笑脸，点击可额外获得亲密度哦！||亲密度查看在动物菜单力查看哦！||每天除了送一份礼物给好友，还能额外满足好友一个愿望礼物哦！||培育屋是培育动物的，建筑是收爱心的！||动物培育的越多，建筑上获得爱心就越越越多！"};
				if (flashVars['newUser'] == 1) {
					//暂时关闭片头 2012-01-03
					//flashVars['pianTouSwf'] = '{%$staticUrl%}/swf/pianTou.swf?v=2011121201';
				}
	        	var params = {base: "{%$staticUrl%}/", allowScriptAccess: "always", menu:"false", wmode: "opaque", allowFullScreen: "true", bgcolor: "#ffffff", align: "middle", quality: "high"};
	        	var attrs = {id: "ipandaLoader", name: "ipandaLoader"};
	        	swfobject.embedSWF("{%$staticUrl%}/swf/ipandaLoader.swf?v=2012010301", "flashdiv",  "748", "600", "10.0", "{%$staticUrl%}/expressInstall.swf", flashVars, params, attrs, checkFlashable);
	        } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">检测到您的浏览器没有开启或接收Cookie！请尝试开启后，重新进入。</div>'
	        	$('#flashdiv').html(html);
	        }

			function checkFlashable(res) {
				if (!res.success) {
					var strhtml = '您没有安装Adobe Flash Player，或者Flash版本过低，建议安装10.0以上版本。<br/>请点击<a href="http://get.adobe.com/cn/flashplayer/" target="_blank">这里</a>进行安装。';
					$('#loadingdiv').css('left', '100px').css('top', '250px').css('color', 'red').html(strhtml);
				}
			}
	        function hideLoading()
	        {
	        	$('#loadingdiv').hide();
	        }
		</script>
	</div>

</div>

{%include file="footer.phtml"%}