<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>停机维护 - 快乐森林</title>
<style type="text/css">
<!--
body {
	margin-top: 30px;
}
body,td,th {
	font-size: 12px;
	color: #666666;
	font-family: 宋体, Arial;
	line-height:24px;
}
-->
</style></head>

<body>
<table width="537" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="274" background="{%$staticUrl%}/maintance/images/bg.gif">
		<div style="margin-left: 280px; width: 170px;">{%$notice%}</div>
    </td>
  </tr>
</table>
</body>

</html>
