<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>快乐森林</title>
</head>
<style>
#bg{
margin:0 auto;
align:center;
background-repeat: no-repeat;
width:537px;
height:284px;
background-image:url({%$staticUrl%}/ipanda/image/pay/donatesuccess.jpg);
}

#bg #continue {
    padding-left:220px;
    padding-top:190px;
}

#bg #close {
    padding-left:220px;
    padding-top:5px;
}
</style>
<body>

{% if $err %}
	<div>
		{%$err|escape%}<br/>
		<a href="http://yingyong.taobao.com/show.htm?app_id=109001">点这里返回游戏</a>
	</div>
{% else %}
    <div id="bg">
        <div id="continue">
            <a href="http://yingyong.taobao.com/show.htm?app_id=109001">
                <img style="border:none" src="{%$staticUrl%}/ipanda/image/pay/continue.gif" alt="继续游戏"/>
            </a>
        </div>
        <div id="close">
            <a href="#" onclick="window.opener=null;window.open('','_self');window.close();">
                <img style="border:none" src="{%$staticUrl%}/ipanda/image/pay/close.gif" alt="关闭窗口" />
            </a>
        </div>
    </div>
{% /if %}

</body>
</html>